/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.intuit.karate.Results;
import com.intuit.karate.Runner;
import com.intuit.karate.junit5.Karate;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class TotalTestsRunner {
    //    @Karate.Test
//    Karate testUsers() {
//        return Karate.run().relativeTo(getClass());
//    }
    @Test
    void testParallel() {
        Results results = Runner.path("classpath:demo")
                .tags("~@ignore")
                //.outputCucumberJson(true)
                .parallel(1);
        assertEquals(0, results.getFailCount(), results.getErrorMessages());
    }
}
